### ISSUE TITLE
Improve code and examples for contract deployment with constructor inputs

### ISSUE THREAD

**Issue by anomit** [blockvigil/ethvigil-docs#2]
Currently the docs specify a complex example for contract deployment with constructor inputs -- a sort of multisig wallet that forms the base of our [Proxy+signer control feature](https://medium.com/blockvigil/signer-control-cum-proxy-smart-contract-a-look-at-ethvigils-latest-offering-9ad6c098c095) 

This might be overwhelming for beginners to follow and implement.

**Comment by SwaroopH** [comment]
Redundant thanks to new docs for deploy and verification.
